
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\SimpleLoRa\SimpleLoRa.h"
#include "nlib\StringSerial\stringserial.h"

// -*-*- List of node objects -*-*-
nBlock_SimpleLoRa        nb_nBlockNode0_SimpleLoRa   (true, 868.0, 0x00, 0x08, 4, 9, 250.0, false, false, 20, PA_7, PA_6, PB_3, PA_15, PC_0, PB_4, PB_1, 0, POWER_0, PA_12, true, PB_6, PB_7);
nBlock_StringSerial      nb_nBlockNode1_StringSerial (PA_9, PA_10);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode0_SimpleLoRa,   0,    &nb_nBlockNode1_StringSerial, 0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
